server:
  port: 1111

spring:
  jackson:
    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  data:
    mongodb:
      host: localhost
      database: treegrowth-web
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/treegrowth
    username: wusi
    password: 666666
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
#  thymeleaf:
#      cache: false
#      prefix: classpath:/templates/
#      suffix: .html
#      mode: HTML

tree:
  cache:
    expires:
      cache:service:user:basic: 60
    default-expire-time: 60
  location:
    key: EIGBZ-WMIWF-M4TJ7
    base-url: http://apis.map.qq.com
    ip-location: '${tree.location.base-url}/ws/location/v1/ip?ip={ip}&key=${askdog.location.key}&output=json'
    geo-location: '${tree.location.base-url}/ws/geocoder/v1/?location={lat},{lng}&key=${askdog.location.key}&get_poi={poi}&coord_type=5&output=json'
    nearby-distance: 50 #kilometers
    nearby-limit: 1000
    rencent-limit: 100
    rate-distance: 50 #kilometers

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

#  All developers need to register their application before getting started.
#  A registered OAuth application is assigned a unique Client ID and Client Secret.
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 8bcd82fe9ba1abfb5160
    clientSecret: 74be72a0400e463699a7b69bfed8b2f57668126b
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

kafka:
  broker:
    address: localhost:9092
  topic: treegrowth

qiniu:
  ak: e7bw9vdW-XqO0zIZEaY78unLWnmygZjKX4R9mGhE
  sk: 3yzExv9j2qHrfQAY4zBGoxbcOfz7lYiRovUlqvwd
  bucket-name: treegrowth